In [1]:
import pandas as pd
#pandas contain data structure and manupilating tool to clean data and fast processing.

In [2]:
from pandas import Series,DataFrame
#From panda library we import series for one dimensional array and dataframe for two dimensional array

In [3]:
obj = pd.Series([4,7,-5,3])
#we assign the series of one dimensional array to obj
obj
#The obj display the array with it's indeces.

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values
#obj.values display the array with data type

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index
#obj.index is used to check the starting point and ending point of index and there steps

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2
# The onde dimensional array Series index are replace with label.

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index
#Display the index with datatype

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']
#Pointing the specific object to obtaine the object

-5

In [12]:
obj2['d'] = 6
#replace the object of 'd' index with value 6

In [13]:
obj2[['c', 'a', 'd']]
#display the array with changes

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2 > 0]
#Displaying the array the with object which is greater than 0 

d    6
b    7
c    3
dtype: int64

In [15]:
obj2 * 2
#Multiply each object value with 2 and display

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
import numpy as np
#It is use for mathimetical operation
np.exp(obj2)
#exp is use to exponential form

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2
#To check wether b index is present or not it will give boolean 

True

In [19]:
'e' in obj2
#'e' index is not present in given series.

False

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
#The dictionery of data with strings and integer type is assign to dict sdata

In [21]:
obj3 = pd.Series(sdata)
#assign the series of dictionery to obj3

In [22]:
obj3
#Display the array with indeces


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
#Dictionary with state name's assign to states

In [24]:
obj4 = pd.Series(sdata, index=states)
obj4
#Here, three values found in sdata were placed in the appropriate locations, but since no value for 'California' was found, it appears as NaN (not a number), which is
#considered in pandas to mark missing or NA values. Since 'Utah' was not included in states, it is excluded from the resulting object

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)
#isnull is use to check if there any index with missing value here california don't have any values

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)
#Here notnull fun give boolean false if there any index don't have value otherwise it give true

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()
#California don't have any value so it is true all other indeces have values so they are falseo

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3
#Display obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4
#use to display obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4
#Add the numbers while californa and Utah don't have number.Obj3 index which is add with Utah don't have number to add

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = 'population'
#Give obj4 a name of population

In [32]:
obj4.index.name = 'state'
#obj4 indeces have are the name of state

In [33]:
obj4
#display with name of state to index and give the name population

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj
#display obj
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj
#Reset the index of obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [40]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
#Two dimensional array assign to data have column name state,year and pop

In [41]:
frame = pd.DataFrame(data)
#dataframe assing to frame

In [42]:
frame
#Display the table with indeces and column name which are browser-friendly HTML table.

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [43]:
frame.head()
#For large DataFrames, the head method selects only the first five rows

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [44]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])
#the DataFrame’s columns will be arranged in order which is given in above columns:

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [45]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
 index=['one', 'two', 'three', 'four',
 'five', 'six'])
#The column that isn’t contained in the dictionery, it will appear with missing values in the result:


In [46]:
frame2
#display the table

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [47]:
frame2.columns
#Display the column of the table with data type

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2['state']
#Display indeces with object of column state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [49]:
frame2.year
#Display the indeces with object of column year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [50]:
frame2.loc['three']
#. Rows is retrieved by  name with the special loc attribute

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [51]:
frame2['debt'] = 16.5
frame2
#Columns can be modified by assignment with the value of 16.5

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [52]:
frame2['debt'] = np.arange(6.)
frame2
#Assign a Series, its labels will be realigned exactly to
#the DataFrame’s index, inserting missing values in any holes:

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [53]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])


In [54]:
frame2['debt'] = val
frame2
#the values in debt column with indeces 'two','four' and 'five' is set with -1.2,-1.5 and -1.7

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [55]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2
#Add new column name fo eastern and assingn with the value of Ohio in state column.all other name will display false 

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [56]:
del frame2['eastern']
frame2.columns
#del is used to delete in the dataframe column which is specified in the frame

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
#the dict name with pop have two column 'Nevada' and 'Ohio'

In [58]:
frame3 = pd.DataFrame(pop)
frame3
#Assing dataframe with frame3 and display

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [59]:
frame3.T
#Transpose is use to  swap rows and columns

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [60]:
pd.DataFrame(pop, index=[2001, 2002, 2003])
#explicit indeces with spedcified then display

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio': frame3['Ohio'][:-1],
 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)
#Assigning the last column of frame3 to "ohio" and first three column of row 'nevada' of 'frame3' to 'ohio' of new dataset

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [62]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3
#display the value of frame3 with index name year and columns name state

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [63]:
frame3.values
#Display the value of frame3 in array form

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [64]:
frame2.values
#display the value of the frame2 in array form

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)